#!/usr/bin/env python
"""Render the diagnosis KB to ``docs/kb/<id>.md`` + ``docs/kb/index.md`` and keep the
i18n catalogues in sync (plan §5.5 "문서 연동", rule 11.6).

Usage (from the repo root, through the project venv)::

    .venv/bin/python scripts/render_kb_docs.py               # render docs/kb/
    .venv/bin/python scripts/render_kb_docs.py --write-i18n  # also update i18n/{ko,en}/diagnose.yaml
    .venv/bin/python scripts/render_kb_docs.py --check       # exit 1 when docs/i18n are stale

The i18n files keep their non-KB keys (``diagnose.cli.*``, ``diagnose.report.*``,
``diagnose.KB-UNKNOWN.*``); only ``diagnose.<KB-ID>.cause/fix`` are (re)generated from the
KB YAML so that the KB stays the single source of truth for the texts.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from wintersar.diagnose.kb_loader import KBEntry, load_kb  # noqa: E402

DOCS_KB = REPO / "docs" / "kb"
I18N = REPO / "src" / "wintersar" / "i18n"
HEADER = "<!-- generated by scripts/render_kb_docs.py from src/wintersar/diagnose/kb/*.yaml; do not edit -->"

_ENGINE_TITLE = {
    "snaphu": "SNAPHU",
    "isce2": "ISCE2 / topsStack",
    "mintpy": "MintPy",
    "hyp3": "HyP3",
    "asf": "asf_search",
    "any": "공통 (engine-independent)",
}


def _yaml_dump(data: dict[str, Any]) -> str:
    return yaml.safe_dump(
        data, allow_unicode=True, sort_keys=False, width=10_000, default_flow_style=False
    )


def render_entry(e: KBEntry) -> str:
    lines = [HEADER, f"# {e.id}", ""]
    lines.append(f"- 엔진(engine): `{e.engine}`")
    lines.append(f"- 단계(stage): `{e.stage or '-'}`")
    lines.append(f"- 심각도(severity): **{e.severity}**")
    lines.append(
        "- 패턴 검증(pattern_verified): "
        + (
            "**예** — 업스트림 소스 문자열에서 도출"
            if e.pattern_verified
            else "**아니오** — docs/open-questions.md 참고"
        )
    )
    if e.pattern_source:
        lines.append(f"- 패턴 출처(pattern_source): {e.pattern_source}")
    lines.append("")
    lines.append("## 패턴 (regex)")
    lines.append("")
    lines.append("```text")
    lines.append(e.pattern)
    lines.append("```")
    lines.append("")
    lines.append("## 원인 (Cause)")
    lines.append("")
    lines.append(e.cause.ko)
    lines.append("")
    lines.append(f"_EN_: {e.cause.en}")
    lines.append("")
    lines.append("## 조치 (Fix)")
    lines.append("")
    lines.append(e.fix.ko)
    lines.append("")
    lines.append(f"_EN_: {e.fix.en}")
    lines.append("")
    if e.retry_hint:
        lines.append("## 자동 재시도 제안 (retry_hint)")
        lines.append("")
        lines.append("```yaml")
        lines.append(_yaml_dump(e.retry_hint.model_dump()).rstrip())
        lines.append("```")
        lines.append("")
    if e.refs:
        lines.append("## 참고 (References)")
        lines.append("")
        lines.extend(f"- {r}" for r in e.refs)
        lines.append("")
    if e.supersedes:
        lines.append(f"_이 항목이 일치하면 다음 항목은 제외됩니다: {', '.join(e.supersedes)}_")
        lines.append("")
    return "\n".join(lines)


def render_index(entries: list[KBEntry]) -> str:
    lines = [HEADER, "# 진단 지식 베이스 (Diagnosis KB)", ""]
    lines.append(
        "`wintersar diagnose work/logs/` 는 엔진 로그를 아래 항목과 대조해 **원인 → 조치 → 참고** 순서로 설명합니다 (R-02, R-14, PERF-13). "
        "패턴이 일치하지 않으면 `KB-UNKNOWN` 과 함께 마스킹된 로그 발췌를 남깁니다."
    )
    lines.append("")
    lines.append("| ID | 엔진 | 단계 | 심각도 | 검증 | 요약 |")
    lines.append("|---|---|---|---|---|---|")
    for e in entries:
        summary = e.cause.ko.split(". ")[0].split("(")[0].strip()
        if len(summary) > 60:
            summary = summary[:57] + "…"
        lines.append(
            f"| [{e.id}]({e.id}.md) | {e.engine} | {e.stage or '-'} | {e.severity} | "
            f"{'예' if e.pattern_verified else '아니오'} | {summary} |"
        )
    lines.append("")
    lines.append("## KB-UNKNOWN")
    lines.append("")
    lines.append(
        "알려진 패턴이 없을 때 생성되는 미분류 Finding 입니다. `evidence.excerpt` 에 마스킹된 로그 발췌가 들어 있으며, "
        "새 패턴을 KB YAML(`src/wintersar/diagnose/kb/*.yaml`)에 추가한 뒤 `scripts/render_kb_docs.py --write-i18n` 을 실행하면 문서와 메시지가 함께 갱신됩니다."
    )
    lines.append("")
    by_engine: dict[str, list[KBEntry]] = {}
    for e in entries:
        by_engine.setdefault(e.engine, []).append(e)
    lines.append("## 엔진별")
    lines.append("")
    for eng, group in by_engine.items():
        lines.append(
            f"- **{_ENGINE_TITLE.get(eng, eng)}**: "
            + ", ".join(f"[{g.id}]({g.id}.md)" for g in group)
        )
    lines.append("")
    return "\n".join(lines)


def render_docs(entries: list[KBEntry]) -> dict[Path, str]:
    out = {DOCS_KB / f"{e.id}.md": render_entry(e) for e in entries}
    out[DOCS_KB / "index.md"] = render_index(entries)
    return out


def merged_i18n(entries: list[KBEntry], lang: str) -> str:
    path = I18N / lang / "diagnose.yaml"
    existing: dict[str, Any] = {}
    if path.exists():
        existing = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    section = dict(existing.get("diagnose") or {})
    for e in entries:
        section[e.id] = {"cause": e.cause.get(lang), "fix": e.fix.get(lang)}
    # deterministic order: non-KB keys first (as they were), then KB ids sorted
    ordered: dict[str, Any] = {
        k: v for k, v in section.items() if not k.startswith("KB-") or k == "KB-UNKNOWN"
    }
    for k in sorted(k for k in section if k.startswith("KB-") and k != "KB-UNKNOWN"):
        ordered[k] = section[k]
    existing["diagnose"] = ordered
    header = (
        f"# diagnose module messages ({lang}). Keys diagnose.KB-*.cause/fix are generated from\n"
        "# src/wintersar/diagnose/kb/*.yaml by scripts/render_kb_docs.py --write-i18n; edit the KB, not this block.\n"
    )
    return header + _yaml_dump(existing)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write-i18n", action="store_true", help="update i18n/{ko,en}/diagnose.yaml")
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are stale")
    args = ap.parse_args(argv)

    entries = load_kb()
    outputs = render_docs(entries)
    if args.write_i18n or args.check:
        for lang in ("ko", "en"):
            outputs[I18N / lang / "diagnose.yaml"] = merged_i18n(entries, lang)

    stale: list[Path] = []
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
    if args.check:
        if stale:
            sys.stderr.write("stale: " + ", ".join(str(p.relative_to(REPO)) for p in stale) + "\n")
            return 1
        sys.stdout.write("kb docs/i18n up to date\n")
        return 0
    sys.stdout.write(f"wrote {len(stale)} file(s); {len(entries)} KB entries\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
